services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      target: dev
    ports:
      - "4430:5000"
    environment:
      FLASK_DEBUG: 1
      OPENAKUN_CONFIG: /app/openakun.cfg
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - redis
      - postgres
    stop_signal: SIGINT
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:15-alpine"
    volumes:
      - type: volume
        source: db-data
        target: /data
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/pgdata
    ports:
      - "2345:5432"
volumes:
  db-data:
