[tool.poetry]
name = "openakun"
version = "0.0.1"
description = "Open real-time questing engine"
authors = ["alethiophile <alethiophile.dev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.2"
passlib = "^1.7.2"
fastpbkdf2 = "^0.2"
alembic = "^1.4.3"
sqlalchemy = "^1.3.19"
psycopg2 = "^2.8.6"
flask-login = "^0.5.0"
bleach = "^3.2.1"
flask-socketio = "^4.3.1"
eventlet = "^0.28.0"
raven = {extras = ["flask"], version = "^6.10.0"}
redis = "^3.5.3"
itsdangerous = "^1.1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
mypy = "^0.782"
sqlalchemy-stubs = "^0.3"

[tool.poetry.scripts]
openakun_initdb = 'openakun.pages:init_db'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
