"""Updates from SQLAlchemy upgrade

Revision ID: 0cc51c780f15
Revises: 4524ddfe9432
Create Date: 2025-03-02 17:10:06.212669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cc51c780f15'
down_revision = '4524ddfe9432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('topic_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_roles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'joined_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('writein_entries', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writein_entries', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'joined_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_roles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('topic_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
