"""removed token silliness on chat messages

Revision ID: 116e5a66d9ed
Revises: 5ffccde67075
Create Date: 2025-03-21 12:52:01.544174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116e5a66d9ed'
down_revision = '5ffccde67075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_messages_id_token', 'chat_messages', type_='unique')
    op.drop_column('chat_messages', 'id_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('id_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_chat_messages_id_token', 'chat_messages', ['id_token'])
    # ### end Alembic commands ###
