"""Forced unique id tokens

Revision ID: 1c465843735b
Revises: 72bfa8cd989c
Create Date: 2017-10-14 15:29:45.705187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c465843735b'
down_revision = '72bfa8cd989c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_chat_messages_id_token'), 'chat_messages', ['id_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chat_messages_id_token'), 'chat_messages', type_='unique')
    # ### end Alembic commands ###
