"""Added timezones

Revision ID: 40f60062ddd5
Revises: ceddbf7c791c
Create Date: 2017-10-12 20:48:54.112515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f60062ddd5'
down_revision = 'ceddbf7c791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='users',
        column_name='joined_date',
        type_=sa.DateTime(timezone=True)
    )
    op.alter_column(
        table_name='posts',
        column_name='posted_date',
        type_=sa.DateTime(timezone=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='users',
        column_name='joined_date',
        type_=sa.DateTime(timezone=False)
    )
    op.alter_column(
        table_name='posts',
        column_name='posted_date',
        type_=sa.DateTime(timezone=False)
    )
    # ### end Alembic commands ###
