"""added topics

Revision ID: 4524ddfe9432
Revises: 695bd1759bbb
Create Date: 2025-01-21 11:47:06.538158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4524ddfe9432'
down_revision = '695bd1759bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name=op.f('fk_topics_poster_id_users')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_topics_story_id_stories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_table('topic_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name=op.f('fk_topic_messages_poster_id_users')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_messages_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_messages')
    op.drop_table('topics')
    # ### end Alembic commands ###
