"""Add tags table

Revision ID: 5ffccde67075
Revises: 0cc51c780f15
Create Date: 2025-03-13 12:08:24.205737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffccde67075'
down_revision = '0cc51c780f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_tag'], ['tags.id'], name=op.f('fk_tags_canonical_tag_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('story_tags',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_tags_story_id_stories')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_story_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('story_id', 'tag_id', name=op.f('pk_story_tags'))
    )
    op.alter_column('user_with_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_with_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_with_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_with_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('story_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
