"""rectified votes

Revision ID: 695bd1759bbb
Revises: 5d09b4ee385d
Create Date: 2020-10-15 15:40:39.726155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695bd1759bbb'
down_revision = '5d09b4ee385d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_entries', sa.Column('vote_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_vote_entries_post_id_posts', 'vote_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vote_entries_vote_id_vote_info'), 'vote_entries', 'vote_info', ['vote_id'], ['id'])
    op.drop_column('vote_entries', 'post_id')
    op.add_column('vote_info', sa.Column('writein_allowed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_info', 'writein_allowed')
    op.add_column('vote_entries', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_vote_entries_vote_id_vote_info'), 'vote_entries', type_='foreignkey')
    op.create_foreign_key('fk_vote_entries_post_id_posts', 'vote_entries', 'posts', ['post_id'], ['id'])
    op.drop_column('vote_entries', 'vote_id')
    # ### end Alembic commands ###
