"""Added vote tables

Revision ID: 7210849b51fe
Revises: 1c465843735b
Create Date: 2020-09-27 15:47:08.142317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7210849b51fe'
down_revision = '1c465843735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writein_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(user_id is null) != (anon_id is null)', name=op.f('ck_writein_entries_user_or_anon')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_writein_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writein_entries'))
    )
    op.create_table('vote_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vote_text', sa.String(), nullable=False),
    sa.Column('killed', sa.Boolean(), nullable=False),
    sa.Column('killed_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_vote_entries_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_entries'))
    )
    op.create_table('vote_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('multivote', sa.Boolean(), nullable=False),
    sa.Column('votes_hidden', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('time_closed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_vote_info_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_info'))
    )
    op.create_table('user_votes',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anon_id', sa.String(), nullable=False),
    sa.CheckConstraint('(user_id is null) != (anon_id is null)', name=op.f('ck_user_votes_user_or_anon')),
    sa.ForeignKeyConstraint(['entry_id'], ['vote_entries.id'], name=op.f('fk_user_votes_entry_id_vote_entries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_votes_user_id_users')),
    sa.PrimaryKeyConstraint('entry_id', 'user_id', 'anon_id', name=op.f('pk_user_votes'))
    )
    enum_type = sa.Enum('Text', 'Vote', 'Writein', name='posttype')
    # enum_type.create(op)
    op.add_column('posts', sa.Column('post_type', enum_type, nullable=False, server_default='Text'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_type')
    op.drop_table('user_votes')
    op.drop_table('vote_info')
    op.drop_table('vote_entries')
    op.drop_table('writein_entries')
    # ### end Alembic commands ###
