"""Added IP identifier table

Revision ID: edda1a2c4ff7
Revises: 74b597cd6ec9
Create Date: 2017-10-14 01:07:34.351394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edda1a2c4ff7'
down_revision = '74b597cd6ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_identifier',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('hash', name=op.f('pk_address_identifier'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_identifier')
    # ### end Alembic commands ###
